---
name: "qualys-api-security"
github: "jenkinsci/qualys-api-security-plugin"
paths:
	- "com/qualys/plugins/qualys-api-security-plugin"
developers:
	- "qualys-plugins"
	- "pmgupte"
	- "lseletos"
	- "gwaghmare"
	- "pranaybqualys"
	- "nikita-bedmutha"
	- "gouripatilqualys"
